apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: cae-app
    kubevirt.io/vm: cae131460
    team: cae-team
  name: cae131460
  namespace: cae-team
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: cae131460
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo:latest
        name: containerdisk
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitdisk
